### ISSUE TITLE
V10 compatibility

### ISSUE THREAD

**Issue by Zankoas** [theripper93/Weather-Blocker#9]
Sadly seems the module isn't working with v10; error log gives the following:
```
Foundry VTT | Rendering DrawingConfig
4commons.js:1250 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1239:19)
    at Drawing.get (foundry.js:24526:23)
    at WeatherBlocker.isWeatherBlocking (main.js:219:28)
    at main.js:22:58
    at Array.filter (<anonymous>)
    at get drawings [as drawings] (main.js:22:39)
    at WeatherBlocker.getPolygons (main.js:88:42)
    at WeatherBlocker.refreshMask (main.js:76:27)
    at main.js:58:27
logCompatibilityWarning @ commons.js:1250
commons.js:1250 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1239:19)
    at Drawing.get (foundry.js:24526:23)
    at WeatherBlocker.adjustPolygonPoints (main.js:192:17)
    at main.js:89:36
    at Array.map (<anonymous>)
    at WeatherBlocker.getPolygons (main.js:88:51)
    at WeatherBlocker.refreshMask (main.js:76:27)
    at main.js:58:27
logCompatibilityWarning @ commons.js:1250
main.js:192 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
[Detected 1 package: weatherblock]
    at WeatherBlocker.adjustPolygonPoints (main.js:192:29)
    at main.js:89:36
    at Array.map (<anonymous>)
    at WeatherBlocker.getPolygons (main.js:88:51)
    at WeatherBlocker.refreshMask (main.js:76:27)
    at main.js:58:27
```

And indeed isn't working on the map:
![image](https://user-images.githubusercontent.com/24595951/188157276-f4c4cc2a-a7b3-476c-8bcc-9e465a5022ac.png)

Of course anything else you need to help diagnose the issue just let me know. Thanks for making such a useful module!

**Comment by theripper93** [comment]
Weather blocker is deprecated since V10. Use fx master instead
